minor: Update Makefile

diff --git a/tools/logs/Makefile b/tools/logs/Makefile
--- a/tools/logs/Makefile
+++ b/tools/logs/Makefile
@@ -6,18 +6,17 @@
 # Put this Makefile in the directory to synchronize and run `make download` to
 # download the latest logs from the robot.
 
-# Hostname or IP address of the Raspberry Pi Uses the value from the UPKIE_NAME
-# environment variable, if defined.
-REMOTE_NAME = ${UPKIE_NAME}
-REMOTE_PATH = logs
+# Help snippet adapted from:
+# http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
+.PHONY: help
+help:
+	@echo "Rules:\n"
+	@grep -P '^[a-zA-Z0-9_-]+:.*? ## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "    \033[36m%-24s\033[0m %s\n", $$1, $$2}'
+.DEFAULT_GOAL := help
 
 .PHONY: clean
 clean:  ## Clean up logs smaller than 100 KiB
 	find . -name '*.mpack' -size "-100k" -delete
-
-.PHONY: download
-download:  ## Download logs from remote host
-	rsync -auvz --progress --exclude Makefile ${REMOTE_NAME}:${REMOTE_PATH}/ $(CURDIR)/
 
 .PHONY: compress
 compress:  ## Compress logs
@@ -27,14 +26,19 @@ compress:  ## Compress logs
 		rm -f $$i; \
 	done
 
+.PHONY: download
+download:  ## Download logs from remote host
+	@if [ -z "${UPKIE_NAME}" ]; then \
+		echo "ERROR: Environment variable UPKIE_NAME is not set.\n"; \
+		echo "This variable should contain the robot's hostname or IP address for SSH. "; \
+		echo "You can define it inline for a one-time use:\n"; \
+		echo "    make some_target UPKIE_NAME=your_robot_hostname\n"; \
+		echo "Or add the following line to your shell configuration:\n"; \
+		echo "    export UPKIE_NAME=your_robot_hostname\n"; \
+		exit 1; \
+	fi
+	rsync -auvz --progress --exclude Makefile ${UPKIE_NAME}:logs/ $(CURDIR)/
+
 .PHONY: foxplot_last
 foxplot_last:  ## Plot latest log
 	foxplot $(shell ls *.mpack | tail -n 1)
-
-# Help snippet adapted from:
-# http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
-.PHONY: help
-help:
-	@echo "Rules:\n"
-	@grep -P '^[a-zA-Z0-9_-]+:.*? ## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "    \033[36m%-24s\033[0m %s\n", $$1, $$2}'
-.DEFAULT_GOAL := help
